---
- name: create {{ item }} folder
  file: path={{ item.path }} state=directory owner=root group=root mode=755
  with_items:
  - "{{ nfs_exports }}"

- name: update /etc/exports
  lineinfile:
    dest: /etc/exports
    line: "{{ item.path }} {{ item.permissions }}"
    regexp: "{{ item.regexp }}"
    state: present
  with_items: 
  - "{{ nfs_exports }}"

- name: restart nfs service
  service: name=nfs-kernel-server state=started
  register: nfs_service

- name: update exports tables
  shell: exportfs -ra
  when: not nfs_service.changed