---
- name: Set up DNS server
  hosts: [dns_master]
  roles: [dns]
  sudo: true
  tags: [dns_master]

- name: Fix DNS settings
  hosts: all:!local:!bastion
  roles: [dns_fix]
  sudo: true
  tags: [dns_fix]