---
- name: Set up docker registry on a vm 
  hosts: [docker_registry]
  roles: [docker, docker_registry]
  sudo: true
  tags: server

- name: Copy docker registry certificate to a vm
  hosts: [docker_registry]
  roles: [docker_registry_crt]
  sudo: true
  tags: cert

- name: Copy docker registry certificate to a vm
  hosts: [docker_openlava]
  roles: [docker_registry_client]
  sudo: true
  tags: cert
