---
- name: Playground vm setup
  hosts: docker_openlava_nodes
  remote_user: ansible
  roles: 
    - { role: ldap_client }
    - { role: nfs_client, nfs_with_ldap: true }
    - { role: docker_ubuntu }
    - { role: openlava, openlava_with_docker: true }
  sudo: true

