---
- name: download and compile
  hosts: [openlava]
  vars: 
    HOME: /home/{{openlava_owner_username}}
  remote_user: root
  become: yes
  become_user: "{{openlava_owner_username}}"
  become_method: su
  gather_facts: False

  tasks:

    - name: create folder
      file: path={{HOME}}/compile state=directory

    - name: download the distribution
      get_url: url=http://www.openlava.org/tarball/openlava-3.0.tar.gz dest={{HOME}}/compile

    - name: unzip it
      command: tar zxvf openlava-3.0.tar.gz chdir={{HOME}}/compile

    - name: configure it
      shell: ./configure chdir={{HOME}}/compile/openlava-3.0

    - name: make it
      shell: make chdir={{HOME}}/compile/openlava-3.0


