---
- name: install the software
  hosts: [openlava]
  vars: 
    HOME: /home/{{openlava_owner_username}}
  remote_user: root

  tasks:

    - name: update the config file
      lineinfile: 
        dest: "/opt/openlava-3.0/etc/lsf.cluster.openlava"
        regexp: '.*{{ hostvars[item].ansible_hostname }}$'
        insertbefore: "End     Host"
        line: "{{ hostvars[item].ansible_hostname  }}      !              !     1       -    -"
        state: present
        backup: yes
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: 
        - '{{ groups.openlava }}'

    - name: replace loopback for hostname
      lineinfile: 
        dest: /etc/hosts
        regexp: '^127.0.0.1 {{ hostvars[item].ansible_hostname }}$'
        line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}'
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: 
        - '{{ groups.openlava }}'

    - name: add lines to /etc/hosts file 
      lineinfile: 
        dest: /etc/hosts
        regexp: '{{ hostvars[item].ansible_hostname }}$'
        line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}'
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: 
        - '{{ groups.openlava }}'

    - name: add it to the boot list
      shell: sysv-rc-conf openlava on

- name: start the service using openlava user
  hosts: [openlava]
  vars: 
    HOME: /home/{{openlava_owner_username}}
  remote_user: root
  become: yes
  become_user: "{{openlava_owner_username}}"
  become_method: su
  gather_facts: False

  tasks:

    - name: restart the service
      shell: service openlava restart

    - name: add lines to .bashrc
      lineinfile: 
        dest: /home/{{openlava_owner_username}}/.bashrc
        regexp: '. /etc/profile.d/openlava.sh'
        insertbefore: "EOF"
        line: '. /etc/profile.d/openlava.sh'

    - name: check openlava works
      shell: sleep 15; . /etc/profile.d/openlava.sh && lsid

    - name: check openlava works
      shell: . /etc/profile.d/openlava.sh && bhosts

