---
- name: Create ldap user
  hosts: [ldap_server]
  roles: [ldap_ubuntu]
  sudo: true
  vars:
    ldap_mode: create_user
    user_info: "Ldap user"
  vars_prompt:
  - name: "group_name"
    propmpt: "User group"
    default: "testgroup" 

  - name: "user_name"
    prompt: "User name"
    default: "testuser"

  - name: "user_password"
    prompt: "User password"
    private: yes
