---
- name: Create ldap user
  hosts: [ldap_server]
  roles: [ldap_util]
  sudo: true
  vars:
    ldap_util: create_user

- name: Create NFS folder for ldap user
  hosts: [nfs_server]
  sudo: true
  tasks:

  - name: mkdir nfs user folder 
    file: path="{{ nfs_users_path }}/{{ ldap_user_name }}" state=directory owner={{ ldap_user_name }} group={{ ldap_user_name }}