---
- name: Create ldap user
  hosts: [ldap_server]
  sudo: true
  tasks:

  - name: create LDAP user
    ldap_user:
        user_name: testuser1
        user_password: testpassword1
        user_info: Test LDAP user
        ldap_base: '{{ ldap_base }}'
        groups: 'testgroup1,testgroup2'
        state: present
    register: out

  - debug: var=out

- name: Create NFS folder for ldap user
  hosts: [nfs_server]
  sudo: true
  tasks:

  - name: mkdir nfs user folder 
    file: path="{{ nfs_users_path }}/{{ ldap_user_name }}" state=directory owner={{ ldap_user_name }} group={{ ldap_user_name }}