---
- name: update ubuntu and install necessary packages
  hosts: [openlava]
  remote_user: root
  gather_facts: False
  tasks:

    - name: upgrade all packages
      apt: update_cache=yes

    - name: install required packages
      apt: pkg={{ item }} state=latest
      with_items: 
      - build-essential
      - libncurses5-dev
      - tcl
      - tcl-dev
      - tcl8.6-dev
      - sysv-rc-conf

