---
- name: Create ldap user
  hosts: [ldap_server]
  sudo: true
  tasks:

  - name: create LDAP user
    ldap_user:
      user_name: '{{ item.user_name }}'
      user_password: '{{ item.user_password }}'
      user_info: '{{ item.user_info }}'
      ldap_base: '{{ ldap_base }}'
      groups: '{{ item.groups }}'
      state: present
    register: out
    with_items:
    - "{{ ldap_users }}"

  - debug: var=out

  #- name: remove LDAP user_name
  #  ldap_user:
  #    user_name: testuser1
  #    ldap_base: '{{ ldap_base }}'
  #    state: absent

- name: Create NFS folder for ldap user
  hosts: [nfs_server]
  sudo: true
  tasks:

  - name: mkdir nfs user folder 
    file: path="{{ nfs_users_path }}/{{ item.user_name }}" state=directory owner={{ item.user_name }} group={{ item.user_name }}
    with_items:
    - "{{ ldap_users }}"
