---
- name: get first nodes from clusetrs
  local_action: shell cat {{ clusters_file }} | awk '{print $1}'
  register: nodes_out

- set_fact:
    nodes: '{{ nodes_out.stdout_lines }}'
 
- name: run lsadmin reconfig
  shell: "yes | {{ openlava_home }}/bin/lsadmin reconfig"
  become: true
  become_method: sudo
  when: '{{ ansible_hostname in nodes}}'