---
- name: place ngseasy scripts to NFS server  
  copy: src={{ item }} dest=/export/ngseasy/bin/{{ item }} owner=root group=root mode=0755
  with_items: 
  - 'ngseasy'
  - 'ngseasy_alignment'
  - 'ngseasy_bsqr'
  - 'ngseasy_fastqc'
  - 'ngseasy_initiate_fastq'
  - 'ngseasy_initiate_project'
  - 'ngseasy_realn'
  - 'ngseasy_trimmomatic'
  - 'ngseasy_variant_calling'
