---
- name: pull ngseasy docker images
  shell: 'docker pull {{ item }}:{{ ngseasy_version }}'
  with_items:
  - "compbio/ngseasy-base"
  - "compbio/ngseasy-fastqc"
  - "compbio/ngseasy-trimmomatic"
  - "compbio/ngseasy-snap"
  - "compbio/ngseasy-bwa"
  - "compbio/ngseasy-bowtie2"
  - "compbio/ngseasy-stampy"
  - "compbio/ngseasy-picardtools"
  - "compbio/ngseasy-freebayes"
  - "compbio/ngseasy-platypus"
  - "compbio/ngseasy-glia"
  - "compbio/ngseasy-delly"
  - "compbio/ngseasy-lumpy"
  - "compbio/ngseasy-bcbiovar"
  - "compbio/ngseasy-cnmops"
  - "compbio/ngseasy-mhmm"
  - "compbio/ngseasy-exomedepth"
  - "compbio/ngseasy-slope"