---
- name: include additional variables
  include_vars: ../../irods_vars.yml

- name: upgrade all packages
  apt: update_cache=yes

- name: install required packages
  apt: pkg={{ item }} state=latest
  with_items: 
  - expect
  - python-psycopg2

- include: ies.yml
  when: icat_is_enabled

- include: server.yml
  when: not icat_is_enabled

- name: test if irods is already installed and running
  shell: ps awx | grep irodsServer
  register: ps_awx

- debug: var=ps_awx

- name: setup irods server
  command: /tmp/setup_irods_with_expect
  register: setup_with_expect
  when: ps_awx.stdout_lines | length < 3

- name: test if irods is already installed and running
  shell: ps awx | grep irodsServer
  register: ps_awx

- fail: irods server is not up after setup command
  when: ps_awx.stdout_lines | length < 3

- name: update /etc/irods/irodsHost config (IES)
  lineinfile:
    dest: /etc/irods/irodsHost
    line: "localhost {{ irods_gateway_hostname }} {{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
    state: present
    backup: yes
  when: icat_is_enabled
  notify: restart irods

- name: update /etc/irods/irodsHost config (Resource Server)
  lineinfile:
    dest: /etc/irods/irodsHost
    line: "localhost {{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
    state: present
    backup: yes 
  when: not icat_is_enabled
  notify: restart irods

- name: Create irods_vault directory if it doesn't exists
  file: path={{ irods_vault_dir }} state=directory owner={{ irods_service_account_name }}  group={{ irods_service_group_name }}

- name: copy iinit expect script
  template: src=iinit.sh dest=/tmp/iinit owner=ansible group=admin mode=0700

- name: run iinit
  command: /tmp/iinit
  sudo: false

- name: check if '{{ ansible_hostname }}_resc' resource already exists
  command: iadmin lr {{ ansible_hostname }}_resc
  register: resource_details
  sudo: false

- name: create new resource 
  command: iadmin mkresc {{ ansible_hostname }}_resc "unixfilesystem" {{ ansible_hostname }}:{{ irods_vault_dir }}
  sudo: false
  when: resource_details.stdout_lines | length < 2