---
- name: include additional variables
  include_vars: "../../irods_vars_4.1.2.yml"

- name: download irods client package
  get_url: url={{ irods_icommands_pkg_url }} dest=/tmp
  register: get_client_pkg

- debug: var=get_client_pkg.dest

- name: install irods client rpms
  apt: deb={{ get_client_pkg.dest }} state=installed
