---
- name: upgrade all packages
  apt: update_cache=yes

- name: Linux distribution
  shell: "lsb_release -is | tr '[:upper:]' '[:lower:]'"
  register: distro

- debug: var=distro.stdout  

- name: Linux distribution codename
  command: lsb_release -cs
  register: codename

- debug: var=codename.stdout  

- name: add Mesosphere repository key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: E56151BF
    state: present

- name: add Mesosphere repository and update apt cache
  apt_repository:
    repo: "deb http://repos.mesosphere.io/{{ distro.stdout }} {{ codename.stdout }} main"
    update_cache: yes
    state: present

- name: install reguired packages
  apt: pkg={{ item }} state=latest
  with_items: 
  - mesosphere
  when: is_master

- name: install reguired packages
  apt: pkg={{ item }} state=latest
  with_items: 
  - mesos
  when: not is_master

- name: set Zookeeper hosts
  template: src=zk dest=/etc/mesos/zk

- include: master.yml
  when: is_master

- include: slave.yml
  when: not is_master

