---
- name: set master id
  template: src=master_id dest=/etc/zookeeper/conf/myid

- name: configure master's Zookeeper
  lineinfile: 
    dest: /etc/zookeeper/conf/zoo.cfg
    insertafter: "#server.3=zookeeper3:2888:3888"
    line: "server.{{ item.0 + 1 }}={{ item.1 }}:2888:3888"
    state: present
    backup: yes
  with_indexed_items: '{{ groups.mesos_master }}'

- name: modify the quorum to reflect the cluster size
  shell: 'echo $(( 2*{{ groups.mesos_master|length }}/3 > 1 ? 2*{{ groups.mesos_master|length }}/3 : 1 )) > /etc/mesos-master/quorum'

- name: configure master's ip
  shell: echo {{ ansible_default_ipv4.address }}| sudo tee /etc/mesos-master/ip

- name: configure master's hostname
  shell: cp /etc/mesos-master/ip /etc/mesos-master/hostname

- name: create Marathon config directory on master
  file: path=/etc/marathon/conf state=directory

- name: copy master's hostname to marathon config directory
  shell: cp /etc/mesos-master/hostname /etc/marathon/conf

- name: define the list of zookeeper masters that Marathon will connect to
  shell: cp /etc/mesos/zk /etc/marathon/conf/master

- name: allow Marathon to store its own state information in zookeeper
  template: src=zk_marathon dest=/etc/marathon/conf/zk

- name: stop any slave-processes if running
  service: name=mesos-slave state=stopped

- name: ensure that the server doesn't start the slave process at boot by creating an override file
  shell: echo manual | sudo tee /etc/init/mesos-slave.override

- name: restart Zookeeper
  service: name=zookeeper state=restarted enabled=true

- name: start mesos
  service: name=mesos-master state=started enabled=true

- name: start marathon
  service: name=marathon state=started enabled=true

- name: start chronos
  service: name=chronos state=started enabled=true