---
- name: stop zookeeper processes if there are any
  service: name=zookeeper state=stopped

- name: create an override file so that zookeeper proccess will not automatically start
  shell: echo manual | sudo tee /etc/init/zookeeper.override

- name: stop mesos-master processes if there are any
  service: name=mesos-master state=stopped

- name: create an override file to make sure the Mesos master process doesn't start on slave
  shell: echo manual | sudo tee /etc/init/mesos-master.override

- name: configure slave's ip
  shell: echo {{ ansible_default_ipv4.address }}| sudo tee /etc/mesos-slave/ip

- name: configure slave's hostname
  shell: cp /etc/mesos-slave/ip /etc/mesos-slave/hostname 

- name: start mesos-slave process
  service: name=mesos-slave state=started enabled=true

- name: update slave configuration to specify the use of the Docker containerizer 
  shell: "{{ item }}"
  with_items:
  - "echo 'docker,mesos' > /etc/mesos-slave/containerizers"
  - "echo '5mins' > /etc/mesos-slave/executor_registration_timeout"
  notify: restart mesos-slave