---
# Based on https://wiki.transmartfoundation.org/pages/viewpage.action?pageId=6619205
# transmart will be available on http://localhost:8080/transmart/ with admin/admin 
# on Cloud appropriate ports have to be opened and redirected 

# Load examples
- name: step10 - prepare ETL environment
  shell: cd transmart-data && source vars && make -C env/ data-integration && make -C env/ update_etl
  sudo: no
  args:
     executable: /bin/bash

- name: step11 - upload examples studies
  shell: cd transmart-data && source vars && make -C samples/postgres load_clinical_GSE8581 && make -C samples/postgres load_ref_annotation_GSE8581 && make -C samples/postgres load_expression_GSE8581
  sudo: no
  args:
     executable: /bin/bash









 






  



