---
- name: include additional variables
  include_vars: ../../ssh_key_vars.yml

#- name: upgrade all packages (RedHat)
#  yum: name=* state=latest
#  sudo: true
#  when: ansible_os_family == "RedHat"

- name: install SELinux-Python (RedHat)
  yum: name=libselinux-python state=present
  when: ansible_os_family == "RedHat"

- name: upgrade all packages (Debian)
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.bak

- name: Create admins group
  group: name=admin system=yes state=present

- name: Make sure admin group can sudo
  lineinfile: 
    dest: /etc/sudoers 
    state: present 
    regexp: "^%admin ALL.?.?ALL.? NOPASSWD.? ALL" 
    line: "%admin ALL=(ALL) NOPASSWD: ALL"

- name: Make sure ssh-agent works via sudo
  lineinfile: dest=/etc/sudoers state=present regexp="^Defaults env_keep\+\=SSH_AUTH_SOCK" line="Defaults env_keep+=SSH_AUTH_SOCK"

- name: Create user ansible
  user: name=ansible comment="Ansible User" group=admin home=/home/ansible shell=/bin/bash state=present

- name: Check if key-pair exists 
  local_action: stat path={{ key_dir }}/{{ key_name }}
  register: key_pair

- debug: var=key_pair.stat.exists

- name: Create a directory to store key-pair
  local_action: command mkdir -p {{ key_dir }}
  when: not key_pair.stat.exists

- name: Generate SSH keys
  local_action: command ssh-keygen -t rsa  -f {{ key_dir }}/{{ key_name }} -P ""
  when: not key_pair.stat.exists

- name: Authorized key upload
  authorized_key: 
    user: ansible 
    key: "{{ lookup('file', key_dir + '/' + key_name + '.pub') }}"
    path: "/home/ansible/.ssh/authorized_keys"
    manage_dir: no
  sudo: true

- name: ssh-add the private key locally
  local_action: command ssh-add {{ key_dir }}/{{ key_name }}