---
- name: test remote database connection
  postgresql_db: 
    name: "{{ irods_db_name }}"
    port: "{{ irods_db_port }}"
    login_host: "{{ irods_db_hostname }}"
    login_user: "{{ irods_db_user }}"
    login_password: "{{ irods_db_password }}"
    state: present

- name: download irods postgres plugin package
  get_url: url={{ irods_postgres_plugin_pkg_url }} dest=/tmp
  register: get_db_plugin_pkg

- debug: var=get_db_plugin_pkg.dest

- name: download irods ICAT package
  get_url: url={{ irods_icat_pkg_url }} dest=/tmp
  register: get_icat_pkg

- debug: var=get_icat_pkg.dest

- name: install irods icat package
  apt: deb={{ get_icat_pkg.dest }} state=installed

- name: install db plugin
  apt: deb={{ get_db_plugin_pkg.dest }} state=installed

- name: copy expect script to setup irods server
  template: src=setup_icat.input dest=/tmp/setup_irods.input owner=root group=root mode=0700