---
- fail: ldap_mode is undefined
  when: ldap_mode is undefined

- include: server.yml
  when: ldap_mode == "server"

- include: create_user.yml
  when: ldap_mode == "create_user"

- include: create_host.yml
  when: ldap_mode == "create_host"



