---
- name: install required packages
  apt: pkg={{ item }} state=latest
  with_items: 
    - build-essential

- name: find openlava install dir
  shell: ls /opt | grep openlava
  register: openlava_dir

- set_fact: 
    openlava_dir: "/opt/{{ openlava_dir.stdout }}"

- name: copy docker specific scripts 
  copy: src={{ item }} dest={{ openlava_dir }}/bin owner=openlava group=openlava mode=0751
  with_items: 
     - docker_terminate
     - docker_resume
     - docker_stop

- name: copy docker_starter.c
  copy: src=docker_starter.c dest=/tmp

- name: compile docker_starter.c
  shell: gcc /tmp/docker_starter.c -o {{ openlava_dir }}/bin/docker_starter

- name: fix docker_starter permissions
  file: path={{ openlava_dir }}/bin/docker_starter owner=openlava group=openlava mode=0751

- name: add docker queue to lsb.queues
  template: src=lsb.queues dest={{ openlava_dir }}/etc/lsb.queues

- name: add docker resource to lsf.shared
  lineinfile: 
    dest: "{{ openlava_dir }}/etc/lsf.shared"
    insertbefore: "End\\s*Resource"
    line: '   docker         Boolean ()       ()          (docker server)'
    state: present

- name: remove old nodes from lsf.cluster.openlava config
  lineinfile: 
    dest: "{{ openlava_dir }}/etc/lsf.cluster.openlava"
    regexp: '.*\(cs\s+docker\)\s?$'
    state: absent
  tags: cluster_update

- name: update lsf.cluster.openlava config with all cluster nodes
  lineinfile: 
    dest: "{{ openlava_dir }}/etc/lsf.cluster.openlava"
    regexp: '^{{ hostvars[item].ansible_hostname }}.*'
    insertbefore: "End\\s*Host"
    line: "{{ hostvars[item].ansible_hostname }}      !       !      1      -      (cs docker) "
    state: present
  with_items: 
    - '{{ groups.docker_openlava_nodes }}'
  tags: cluster_update

- name: copy 'dockercmd' script
  copy: src=dockercmd.py dest=/usr/local/bin/dockercmd mode=0750
  tags: update_dockercmd

- name: allow users to run 'dockercmd' command
  lineinfile: 
    dest: /etc/sudoers 
    state: present 
    regexp: "^ALL.*" 
    line: "ALL ALL=NOPASSWD: /usr/local/bin/dockercmd"

- name: restart openlava
  service: name=openlava state=restarted
  tags: cluster_update