---
- name: update  /etc/network/interfaces
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    dest: /etc/network/interfaces
    state: present
  with_items:
  - { regexp: "^dns-nameservers", line: "dns-nameservers {{ groups.dns | regex_replace('[\\[\\]\\'\\,]', '') }}" }
  - { regexp: "^dns-search", line: "dns-search {{ dns_zone }}" }
  register: network_settings

- name: apply network interface
  shell: sudo ifdown eth0 && sudo ifup -v eth0
  when: network_settings | changed
