- debug: var={{ nfs_server_ip }}

- name: create mount directory if it doesn't exist
  file: path=/mnt/home state=directory mode=777

- name: mount users nfs folder
  mount: name=/mnt/home src={{ nfs_server_ip }}:/export/home  fstype=nfs  opts="rw,bg,hard,intr,lock,ac,tcp,nfsvers=4,timeo=1800" state=mounted
