---
- debug: var={{ nfs_server_ip }}

- name: create mount directory if it doesn't exist
  file: path={{ item.name }} state=directory mode=755
  with_items:
  - "{{ nfs_mounts }}"

- name: configure fstab
  mount: name={{ item.name }} src="{{ nfs_server_ip }}:{{ item.src }}" fstype={{ item.fstype }}  opts="{{ item.opts }}" state=mounted
  with_items:
  - "{{ nfs_mounts }}"
