---
- name: pull ngseasy docker images
  shell: 'docker pull {{ item }}:{{ ngseasy_version }}'
  with_items:
  - "compbio/ngseasy-base"
  - "compbio/ngseasy-fastqc"
  - "compbio/ngseasy-trimmomatic"
  - "compbio/ngseasy-snap"
  - "compbio/ngseasy-bwa"
  - "compbio/ngseasy-bowtie2"
  - "compbio/ngseasy-stampy"
  - "compbio/ngseasy-picardtools"
  - "compbio/ngseasy-freebayes"
  - "compbio/ngseasy-platypus"
  - "compbio/ngseasy-glia"
  - "compbio/ngseasy-delly"
  - "compbio/ngseasy-lumpy"
  - "compbio/ngseasy-bcbiovar"
  - "compbio/ngseasy-cnmops"
  - "compbio/ngseasy-mhmm"
  - "compbio/ngseasy-exomedepth"
  - "compbio/ngseasy-slope"
  tags: images

- name: install required packages
  apt: pkg={{ item }} state=latest
  with_items:
  - python-pip 
  - python-dev 
  - build-essential

- name: upgrade pip
  shell: pip install --upgrade pip 

- name: install docker-py
  pip: name=docker-py

- name: clone git repository
  git: repo=https://github.com/olgamelnichuk/ngspyeasy.git dest=/tmp/ngspyeasy version=2.0

- name: install ngspyeasy
  shell: /bin/bash install.sh
  args: 
    chdir: /tmp/ngspyeasy

- name: rename ngspyeasy_tool
  shell: mv /usr/bin/ngspyeasy_tool /usr/bin/ngspyeasy_tool_wrapper

- name: secure ngspyeasy_tool_wrapper
  shell: chmod 0700 /usr/bin/ngspyeasy_tool_wrapper

- name: create ngspyeasy_tool executable
  lineinfile:
    dest: /usr/bin/ngspyeasy_tool
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
  - "#!/usr/bin/env bash"
  - "sudo /usr/bin/ngspyeasy_tool_wrapper \\\"$@\\\""

- name: made ngspyeasy readable and executable
  shell: chmod 755 {{ item }}
  with_items:
    - /usr/bin/ngspyeasy
    - /usr/bin/ngspyeasy_tool

- name: make ngspyeasy sources readable only
  shell: "{{ item }}"
  with_items:
  - "find /opt/ngspyeasy -type d -exec chmod 755 {} +"
  - "find /opt/ngspyeasy -type f -exec chmod 644 {} +"


- name: extract sudoer commands
  shell:  "sudo cat /etc/sudoers | grep 'ALL ALL=NOPASSWD:' | awk '{ print $3 }'"
  register: sudo_cat_out
  tags: sudoers

- set_fact:
    orig_commands: "{{ sudo_cat_out.stdout.split(',') }}"
    more_commands:
    - "/usr/bin/ngspyeasy_tool_wrapper"
  tags: sudoers

- name: allow all users run ngspyeasy_tool
  lineinfile: 
    dest: /etc/sudoers 
    state: present 
    regexp: "^ALL.*" 
    line: "ALL ALL=NOPASSWD: {{ orig_commands | union(more_commands) | join(',') }}"
  tags: sudoers
