---
- set_fact: 
    vg_create: false
    partition: "{{ device }}1"

- debug: var=device

- debug: var=partition

- name: create a partition if it doesn't exist
  include: fdisk.yml

- name: create a physical volume if it doesn't exist
  include: pvcreate.yml 

- name: create or extend VG
  include: vgcreate.yml

- name: create or extend LV
  include: lvcreate.yml

- name: make sure the mount is on
  mount: name={{ mount_point }} src="/dev/{{ vg_name }}/{{ lv_name }}" fstype=ext4  opts=defaults state=mounted
  when: mount_point is defined
