---
- name: check if data VG exists
  shell: vgdisplay | grep "VG Name.*data" | wc -l
  register: vgdisplay_out

- set_fact: vg_create=true
  when: vgdisplay_out.stdout_lines[0] | int == 0

- debug: var=vg_create

- name: create data VG
  shell: vgcreate data {{ partition }}
  when: vg_create

- name: check if VG contains the partition
  shell: pvdisplay {{ partition }} | grep "VG Name" | wc -l
  register: pvdisplay_out
  when: not vg_create

- name: extend data VG with partition
  shell: vgextend data {{ partition }}
  when: (not vg_create) and (pvdisplay_out.stdout_lines[0] | int == 0)